name = "ProjectManagementSystem"
uuid = "afae2cb9-b477-4ad6-b3ff-9d8506b4dc60"
version = "0.1.0"
authors = ["am3lue <am3lue@gmail.com>"]

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Base64 = "1.11.0"
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Genie = "5.33.17"
Inflector = "1.1.0"
Logging = "1.11.0"
SHA = "0.7.0"
Sockets = "1.11.0"
